import re

import pytest

from backend.api_generation import (
    README_FILENAME,
    UnsafeOutputDirectoryError,
    FastAPIApplicationGenerator,
    LLMAPIGenerationResult,
    generate_application,
    validate_generated_artifact,
)
from test_api_generation_boundary import _draft, _env
from test_generated_application_entrypoint import _result


def _readme(**generator):
    result, draft = _result()
    files = FastAPIApplicationGenerator(**generator).generate(draft) if generator else result.files
    return files, files[README_FILENAME], draft


def test_readme_identifies_the_project_and_its_generator():
    _, readme, draft = _readme()

    assert readme.startswith(f"# {draft.summary}\n") and draft.description in readme
    assert "generated by Notebook2API" in readme and "`prereqai-project.json`" in readme
    assert "`POST /add`" in readme


def test_readme_shows_the_actual_entrypoint_commands_and_artifacts():
    files, readme, _ = _readme()

    assert "pip install -r requirements.txt" in readme and "uvicorn app.main:app --host 0.0.0.0 --port 8000" in readme
    assert "docker build -t generated-api ." in readme and "docker run -p 8000:8000 generated-api" in readme
    assert "`openapi.json`" in readme and "python:3.11-slim" in readme
    for path in files:
        assert f"`{path}`" in readme  # every generated file is listed, including the README itself
    assert "| a | int | yes |" in readme and "| sum | int |" in readme


def test_readme_follows_the_configuration_and_is_deterministic():
    _, default, _ = _readme()
    again = _readme()[1]
    _, custom, _ = _readme(base_image="python:3.12-slim", port=9000)

    assert default == again
    assert "--port 9000" in custom and "-p 9000:9000" in custom and "`python:3.12-slim`" in custom
    assert "8000" not in custom


def test_readme_claims_nothing_unsupported_and_has_no_machine_data():
    _, readme, _ = _readme()

    assert "does not run any notebook code" in readme
    assert not re.search(r"deploy|authenticat|kubernetes|cloud|secret|token", readme, re.IGNORECASE)
    assert not re.search(r"(^|[\s`(])/(home|tmp|Users|var|root)/", readme)


def test_validation_flags_a_readme_that_misses_the_real_entrypoint_or_leaks_a_path():
    files, _, _ = _readme()

    thin = {**files, README_FILENAME: "# x\n"}
    leaky = {**files, README_FILENAME: files[README_FILENAME] + "\nBuilt in /home/me/work\n"}

    assert {f["category"] for f in validate_generated_artifact(thin).findings} == {"README_INCOMPLETE"}
    assert {f["category"] for f in validate_generated_artifact(leaky).findings} == {"README_INCOMPLETE"}
    assert "MISSING_FILE" in {f["category"] for f in validate_generated_artifact({k: v for k, v in files.items() if k != README_FILENAME}).findings}


def test_regeneration_replaces_an_edited_generated_readme_but_refuses_a_users_own(tmp_path):
    env = _env()
    _, validated = _draft(env)
    out = tmp_path / "out"
    generate_application(env["draft"], validated, out)
    original = (out / README_FILENAME).read_text()
    (out / README_FILENAME).write_text("edited by hand")

    generate_application(env["draft"], validated, out)

    assert (out / README_FILENAME).read_text() == original

    mine = tmp_path / "mine"
    mine.mkdir()
    (mine / README_FILENAME).write_text("my project's readme")
    with pytest.raises(UnsafeOutputDirectoryError):
        generate_application(env["draft"], validated, mine)
    assert (mine / README_FILENAME).read_text() == "my project's readme"


def test_result_type_is_unchanged_for_other_callers():
    files, _, _ = _readme()
    assert LLMAPIGenerationResult("d", "POST /add", files).files is files
