"""Compatibility diagnostics: check_generated_project(), `api-generation
check` and the release checklist report the detected and supported contract
versions, the compatibility status, the offending field and one remediation
sentence, using the same version rule as the #9 compatibility gate."""
import json
import shutil

import pytest

from backend.api_generation import (
    CONFIG_FILENAME,
    METADATA_FILENAME,
    PROJECT_MANIFEST_FILENAME,
    APIGenerator,
    FastAPIApplicationGenerator,
    check_generated_project,
    run_release_checklist,
)
from backend.api_generation.validation import diagnose_compatibility
from backend.cli import EXIT_FAILURE, EXIT_OK, main
from test_api_generation_boundary import _draft, _env
from test_generated_project_importability import EXAMPLE

SUPPORTED = {
    METADATA_FILENAME: {"contract_version": 1},
    PROJECT_MANIFEST_FILENAME: {"manifest_version": 1, "contract_version": 1},
    CONFIG_FILENAME: {"config_version": 1},
}


@pytest.fixture
def project(tmp_path):
    copy = tmp_path / "project"
    shutil.copytree(EXAMPLE / "generated", copy)
    return copy


def _edit(project, file, **changes):
    data = json.loads((project / file).read_text())
    data.update(changes)
    (project / file).write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")


def test_compatible_project(project):
    diagnosis = check_generated_project(project).compatibility
    assert diagnosis == {"status": "compatible", "detected": SUPPORTED, "supported": SUPPORTED,
                         "oldest_compatible": SUPPORTED, "issues": [], "remediation": None}


def test_older_contract_names_the_field_and_says_to_regenerate(project):
    _edit(project, METADATA_FILENAME, contract_version=0)
    _edit(project, PROJECT_MANIFEST_FILENAME, contract_version=0)

    health = check_generated_project(project)
    diagnosis = health.compatibility

    assert health.status == "incompatible" and diagnosis["status"] == "incompatible"
    assert diagnosis["detected"][METADATA_FILENAME] == {"contract_version": 0}
    assert [(i["file"], i["field"], i["found"], i["relation"]) for i in diagnosis["issues"]] == [
        (METADATA_FILENAME, "contract_version", 0, "older"),
        (PROJECT_MANIFEST_FILENAME, "contract_version", 0, "older"),
    ]
    assert diagnosis["remediation"].startswith("This project uses an older or unrecorded project contract. Regenerate it")


def test_newer_contract_points_to_the_newer_generator(project):
    _edit(project, CONFIG_FILENAME, config_version=4)

    diagnosis = check_generated_project(project).compatibility

    assert diagnosis["status"] == "incompatible"
    assert diagnosis["issues"] == [{"file": CONFIG_FILENAME, "field": "config_version", "found": 4,
                                    "supported": 1, "relation": "newer"}]
    assert "generated by a newer PreReqAI" in diagnosis["remediation"] and "records 4" in diagnosis["remediation"]


@pytest.mark.parametrize("content, relation", [("{not json", "malformed"), (None, "absent")])
def test_malformed_or_missing_metadata_is_unknown_not_guessed(project, content, relation):
    if content is None:
        (project / METADATA_FILENAME).unlink()
    else:
        (project / METADATA_FILENAME).write_text(content)

    health = check_generated_project(project)
    diagnosis = health.compatibility

    assert not health.healthy and diagnosis["status"] == "unknown"
    assert diagnosis["detected"][METADATA_FILENAME] == {"contract_version": None}
    assert {"file": METADATA_FILENAME, "relation": relation} in diagnosis["issues"]
    assert "cannot be determined" in diagnosis["remediation"]


def test_other_generator_and_unrecorded_version(project):
    _edit(project, METADATA_FILENAME, generator="someone-else")
    assert check_generated_project(project).compatibility["issues"][0]["relation"] == "other-generator"

    manifest = json.loads((project / PROJECT_MANIFEST_FILENAME).read_text())
    del manifest["manifest_version"]
    diagnosis = diagnose_compatibility({PROJECT_MANIFEST_FILENAME: json.dumps(manifest)})
    assert {"file": PROJECT_MANIFEST_FILENAME, "field": "manifest_version", "found": None, "supported": 1,
            "relation": "missing"} in diagnosis["issues"]


def test_projects_without_the_optional_config_file_stay_compatible(project):
    (project / CONFIG_FILENAME).unlink()
    manifest = json.loads((project / PROJECT_MANIFEST_FILENAME).read_text())
    manifest["artifacts"] = [a for a in manifest["artifacts"] if a["path"] != CONFIG_FILENAME]
    (project / PROJECT_MANIFEST_FILENAME).write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")

    diagnosis = check_generated_project(project).compatibility
    assert diagnosis["status"] == "compatible" and diagnosis["detected"][CONFIG_FILENAME] == {"config_version": None}


def test_cli_check_prints_the_diagnosis(project, capsys):
    assert main(["api-generation", "check", str(project)]) == EXIT_OK
    text = capsys.readouterr().out
    assert "Compatibility: COMPATIBLE" in text
    assert "prereqai-manifest.json: manifest_version 1 (supported 1), contract_version 1 (supported 1)" in text

    _edit(project, METADATA_FILENAME, contract_version=9)
    assert main(["api-generation", "check", str(project)]) == EXIT_FAILURE
    text = capsys.readouterr().out
    assert "Compatibility: INCOMPATIBLE" in text and "contract_version 9 (supported 1)" in text and "  fix: " in text

    assert main(["api-generation", "check", str(project), "--json"]) == EXIT_FAILURE
    report = json.loads(capsys.readouterr().out)
    assert report["compatibility"]["status"] == "incompatible"
    assert sorted(report["compatibility"]) == ["detected", "issues", "oldest_compatible", "remediation", "status", "supported"]


def test_not_a_directory_is_unknown(tmp_path):
    diagnosis = check_generated_project(tmp_path / "missing").compatibility
    assert diagnosis["status"] == "unknown" and "is not a directory" in diagnosis["remediation"]


def test_release_checklist_carries_the_diagnosis():
    env = _env()
    _, validated = _draft(env)

    ready = run_release_checklist(env["draft"], validated)
    assert ready.ready and ready.compatibility["status"] == "compatible"

    class FutureContract(APIGenerator):
        def generate(self, draft):
            files = FastAPIApplicationGenerator().generate(draft)
            metadata = json.loads(files[METADATA_FILENAME])
            return {**files, METADATA_FILENAME: json.dumps({**metadata, "contract_version": 2})}

    blocked = run_release_checklist(env["draft"], validated, FutureContract())
    assert not blocked.ready and blocked.compatibility["status"] == "incompatible"
    assert any(f.startswith("compatibility: This project was generated by a newer PreReqAI") for f in blocked.failures)
