"""Regeneration guidance in the normal `api-generation check` workflow:
current projects stay quiet, older-but-compatible projects get the detected
and current versions plus the real regenerate command (informational, the
project is not touched), and unsupported projects keep the stronger
compatibility error instead of regeneration advice."""
import hashlib
import json
import shlex
import shutil

import pytest

from backend.api_generation import CONFIG_FILENAME, METADATA_FILENAME, PROJECT_MANIFEST_FILENAME, check_generated_project
from backend.api_generation import metadata as metadata_module
from backend.cli import EXIT_FAILURE, EXIT_OK, main
from test_generated_project_importability import EXAMPLE


@pytest.fixture
def project(tmp_path):
    copy = tmp_path / "my project"  # a space: the printed command must quote paths
    shutil.copytree(EXAMPLE / "generated", copy)
    return copy


def _set_contract(project, version):
    for file in (METADATA_FILENAME, PROJECT_MANIFEST_FILENAME):
        data = json.loads((project / file).read_text())
        data["contract_version"] = version
        (project / file).write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")


def _check(project, capsys, *extra):
    code = main(["api-generation", "check", str(project), *extra])
    return code, capsys.readouterr().out


def _fingerprint(root):
    return {p.relative_to(root).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest()
            for p in sorted(root.rglob("*")) if p.is_file() and "__pycache__" not in p.parts}


def test_current_project_is_quiet(project, capsys):
    code, out = _check(project, capsys)
    assert code == EXIT_OK and "Compatibility: COMPATIBLE" in out
    assert "Regeneration" not in out and "run:" not in out and "fix:" not in out
    code, out = _check(project, capsys, "--json")
    assert json.loads(out)["compatibility"]["regeneration"] is None


def test_older_compatible_project_gets_versions_and_the_real_command(project, capsys, monkeypatch):
    monkeypatch.setitem(metadata_module.OLDEST_COMPATIBLE, "contract_version", 0)
    _set_contract(project, 0)
    before = _fingerprint(project)

    code, out = _check(project, capsys)

    assert code == EXIT_OK  # informational: the project is still healthy
    assert "Regeneration recommended (informational; nothing was changed):" in out
    assert "  prereqai-project.json contract_version: project 0, generator 1" in out
    assert "  prereqai-manifest.json contract_version: project 0, generator 1" in out
    run_line = next(line for line in out.splitlines() if line.startswith("  run: "))
    argv = shlex.split(run_line[len("  run: "):])
    root = str(project.resolve())
    assert argv == ["python", "-m", "backend.cli", "api-generation", "generate", "--draft", "<validated-draft.json>",
                    "--output-dir", root, "--config", f"{root}/{CONFIG_FILENAME}"]
    assert "validated draft 'example-loan-quote'" in out
    assert _fingerprint(project) == before

    code, out = _check(project, capsys, "--json")
    regeneration = json.loads(out)["compatibility"]["regeneration"]
    assert regeneration["draft_id"] == "example-loan-quote"
    assert regeneration["versions"] == [
        {"file": METADATA_FILENAME, "field": "contract_version", "project": 0, "generator": 1},
        {"file": PROJECT_MANIFEST_FILENAME, "field": "contract_version", "project": 0, "generator": 1},
    ]


def test_the_suggested_command_regenerates_the_project_with_its_own_settings(tmp_path, capsys, monkeypatch):
    project = tmp_path / "project"
    assert main(["api-generation", "generate", "--draft", str(EXAMPLE / "draft.json"), "--output-dir", str(project),
                 "--project-name", "loan-quote", "--port", "9100"]) == EXIT_OK
    capsys.readouterr()
    monkeypatch.setitem(metadata_module.OLDEST_COMPATIBLE, "contract_version", 0)
    _set_contract(project, 0)
    command = check_generated_project(project).compatibility["regeneration"]["command"]

    argv = shlex.split(command.replace("<validated-draft.json>", shlex.quote(str(EXAMPLE / "draft.json"))))
    assert main(argv[3:]) == EXIT_OK  # argv[:3] is "python -m backend.cli"
    capsys.readouterr()

    health = check_generated_project(project)
    assert health.healthy and health.compatibility["status"] == "compatible"
    assert json.loads((project / CONFIG_FILENAME).read_text())["runtime"]["port"] == 9100
    assert (project / "loan_quote" / "main.py").is_file()


@pytest.mark.parametrize("version, phrase", [(5, "generated by a newer PreReqAI"), (-3, "older or unrecorded")])
def test_unsupported_project_keeps_the_stronger_error(project, capsys, version, phrase):
    _set_contract(project, version)

    code, out = _check(project, capsys)

    assert code == EXIT_FAILURE and "Compatibility: INCOMPATIBLE" in out
    assert "Regeneration recommended" not in out and "  fix: " in out and phrase in out
    assert json.loads(_check(project, capsys, "--json")[1])["compatibility"]["regeneration"] is None
