from dataclasses import dataclass

LOW = "LOW"
MEDIUM = "MEDIUM"
HIGH = "HIGH"
RISKS = frozenset({LOW, MEDIUM, HIGH})


@dataclass(frozen=True)
class LLMCodeFixSuggestion:
    """One reviewable, advisory fix for a single Commit #1 LLMGeneratedCodeReview finding.

    target is always the exact `location` of the one finding (identified by
    its index in that review's own findings list) this suggestion
    addresses -- see LLMCodeFixSuggestionService.suggest(), which rejects
    any LLM-proposed suggestion that doesn't cite a real finding of the
    given review. change/rationale are natural-language only -- this
    record never carries replacement source, is never generated by a
    separate code-generation pipeline, and is never applied automatically;
    it is only ever a proposal for a human or a later commit to act on.
    """

    suggestion_id: str
    review_id: str
    target: str
    change: str
    rationale: str
    confidence: float
    risk: str
