import json
from dataclasses import asdict, dataclass
from typing import Optional

METADATA_FILENAME = "prereqai-project.json"
GENERATOR_ID = "prereqai.api_generation"
CONTRACT_VERSION = 1
PROJECT_TYPE = "fastapi-app"


class InvalidProjectMetadataError(ValueError):
    """Raised when a generated project's metadata file is malformed or does
    not belong to this generator and contract version."""


class IncompatibleProjectMetadataError(InvalidProjectMetadataError):
    """The metadata is well formed but was produced by another generator or contract version."""


# How a recorded version relates to the one this generator supports.
OLDER, NEWER, MISSING, UNREADABLE = "older", "newer", "missing", "unreadable"


def version_compatibility(data: dict, field: str, supported: int, source: str):
    """The one compatibility rule for every versioned generated-project file
    (prereqai-project.json, prereqai-manifest.json, prereqai-config.json):
    exactly `supported` is compatible; anything else is described as a dict
    {"file", "field", "found", "supported", "relation"} -- relation is older,
    newer, missing or unreadable -- or None when compatible. There are no
    migrations: an incompatible project is reported, never upgraded."""
    if field not in data:
        found, relation = None, MISSING
    else:
        found = data[field]
        if found == supported and not isinstance(found, bool):
            return None
        if isinstance(found, bool) or not isinstance(found, int):
            relation = UNREADABLE
        else:
            relation = NEWER if found > supported else OLDER
    return {"file": source, "field": field, "found": found, "supported": supported, "relation": relation}


_ADVICE = {
    NEWER: "it was generated by a newer PreReqAI; open it with that version",
    OLDER: "it was generated by an older PreReqAI; regenerate it with this version",
    MISSING: "it predates versioned projects or was edited by hand; regenerate it with this version",
    UNREADABLE: "the version is not an integer; regenerate it with this version",
}


def compatibility_message(details: dict) -> str:
    found = "no" if details["relation"] == MISSING else repr(details["found"])
    return (f"{details['file']} has {found} {details['field']} (supported: {details['supported']}): "
            f"{_ADVICE[details['relation']]}")


def require_version(data: dict, field: str, supported: int, source: str, error_class):
    """Raise error_class (carrying .compatibility, the details dict) unless compatible."""
    details = version_compatibility(data, field, supported, source)
    if details is not None:
        error = error_class(compatibility_message(details))
        error.compatibility = details
        raise error


@dataclass(frozen=True)
class GeneratedProjectMetadata:
    """Identity of a generated project: which generator and contract produced
    it, what kind of project it is, and the documentation draft and endpoint
    it came from. It deliberately has no timestamp, so identical input always
    produces an identical file."""

    draft_id: str
    endpoint: str
    generator: str = GENERATOR_ID
    contract_version: int = CONTRACT_VERSION
    project_type: str = PROJECT_TYPE
    # An explicitly configured project name; absent (and omitted from the
    # file) for the default identity, so existing projects parse unchanged.
    project_name: Optional[str] = None

    def to_dict(self) -> dict:
        data = asdict(self)
        if data["project_name"] is None:
            del data["project_name"]
        return data

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2, sort_keys=True) + "\n"

    @classmethod
    def parse(cls, text: str) -> "GeneratedProjectMetadata":
        try:
            data = json.loads(text)
        except ValueError as error:
            raise InvalidProjectMetadataError(f"cannot parse {METADATA_FILENAME}: {error}") from error
        if isinstance(data, dict) and (data.get("generator"), data.get("project_type")) == (GENERATOR_ID, PROJECT_TYPE):
            # checked before the field set, so another contract version is
            # reported as incompatible rather than as a malformed file
            require_version(data, "contract_version", CONTRACT_VERSION, METADATA_FILENAME, IncompatibleProjectMetadataError)
        try:
            if not isinstance(data, dict) or set(data) - {"project_name"} != set(cls.__dataclass_fields__) - {"project_name"}:
                raise ValueError("unexpected fields")
            metadata = cls(**data)
        except (ValueError, TypeError) as error:
            raise InvalidProjectMetadataError(f"cannot parse {METADATA_FILENAME}: {error}") from error
        if metadata.generator != GENERATOR_ID or metadata.project_type != PROJECT_TYPE:
            raise IncompatibleProjectMetadataError(f"{METADATA_FILENAME} was not produced by {GENERATOR_ID} ({PROJECT_TYPE})")
        require_version(data, "contract_version", CONTRACT_VERSION, METADATA_FILENAME, IncompatibleProjectMetadataError)
        if metadata.project_name is not None:
            from .identity import InvalidProjectNameError, project_package
            try:
                project_package(metadata.project_name)
            except InvalidProjectNameError as error:
                raise InvalidProjectMetadataError(str(error)) from error
        for name in ("draft_id", "endpoint"):
            if not isinstance(getattr(metadata, name), str) or not getattr(metadata, name):
                raise InvalidProjectMetadataError(f"{name} must be a non-empty string")
        return metadata
