from backend.api_documentation_draft import LLMAPIDocumentationDraft

from .identity import ProjectIdentity
from .project_manifest import OPENAPI_FILENAME, artifact_type

README_FILENAME = "README.md"
_DESCRIPTIONS = {
    "application-source": "FastAPI application code",
    "dependency-manifest": "Python dependencies to install",
    "container-image": "Docker build for the application",
    "project-metadata": "which generator, contract and draft produced this project",
    "openapi-contract": "OpenAPI document of the generated API",
    "documentation": "this file",
}


def _cell(value) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _table(header, rows) -> list:
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    return lines + ["| " + " | ".join(_cell(c) for c in row) + " |" for row in rows]


def generate_readme(draft: LLMAPIDocumentationDraft, file_paths, base_image: str, port: int,
                    identity: ProjectIdentity = None) -> str:
    """README.md for a generated project, written only from what the
    generator produced: the draft's text and schemas, the real file list, the
    entrypoint and the configured port. It documents installing and running
    the project the way its requirements.txt and Dockerfile support, and
    states plainly what the handlers do. Deterministic, no paths or secrets.
    `identity` names the project and its package (default: the draft's
    summary and `app`, the previous output)."""
    identity = identity or ProjectIdentity(draft.summary)
    paths = sorted(set(file_paths) | {README_FILENAME})
    artifacts = [(p, artifact_type(p) if p != README_FILENAME else "documentation") for p in paths]
    artifacts = [(p, t) for p, t in artifacts if t]
    lines = [
        f"# {identity.name}",
        "",
        draft.description,
        "",
        "This project was generated by Notebook2API from a validated API documentation draft "
        "(see `prereqai-project.json` for the generator, contract version and draft it came from, "
        "and `prereqai-manifest.json` for the full file inventory).",
        "",
        "## Endpoint",
        "",
        f"`{draft.endpoint}` — {draft.summary}",
        "",
        "Parameters:",
        "",
        *_table(["name", "type", "required"], [(n, e.get("type"), "yes" if e.get("required") else "no")
                                               for n, e in draft.parameters.items()] or [("(none)", "", "")]),
        "",
        "Response fields:",
        "",
        *_table(["name", "type"], [(n, e.get("type")) for n, e in draft.responses.items()] or [("(none)", "")]),
        "",
        "## Run locally",
        "",
        "```",
        "pip install -r requirements.txt",
        f"uvicorn {identity.entrypoint} --host 0.0.0.0 --port {port}",
        "```",
        "",
        f"The entrypoint is `{identity.entrypoint}` (the `app` object in `{identity.main_path}`). "
        f"Interactive API docs are served by FastAPI at `/docs`, and the OpenAPI document is in `{OPENAPI_FILENAME}`.",
        "",
        "## Run with Docker",
        "",
        "```",
        f"docker build -t {identity.image_name} .",
        f"docker run -p {port}:{port} {identity.image_name}",
        "```",
        "",
        f"The image is based on `{base_image}`. The listen address comes from the `HOST` and `PORT` "
        f"environment variables (defaults `0.0.0.0` and `{port}`).",
        "",
        "## Behaviour",
        "",
        "The generated handler does not run any notebook code. For a request whose input exactly matches one of the "
        "documented examples it returns that example's output (with an `X-Execution: documented-example` header); "
        "for any other valid request it answers `501 Not Implemented`.",
        "",
        "## Files",
        "",
        *_table(["file", "purpose"], [(f"`{p}`", _DESCRIPTIONS[t]) for p, t in artifacts]),
        "",
    ]
    return "\n".join(lines)
